blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ANOLASC/freqtrade-rs/tree/master/docs
    about: Check out our documentation for more information.
  - name: Discord
    url: https://discord.gg/freqtrade
    about: Join our Discord community for real-time discussion.
